machines = {
  "master" => {"memory" => "1024", "cpu" => "1", "ip" => "100", "image" => "alvistack/devel-22.04"},
  "worker01" => {"memory" => "1024", "cpu" => "1", "ip" => "101", "image" => "alvistack/devel-22.04"},
  "worker02" => {"memory" => "1024", "cpu" => "1", "ip" => "102", "image" => "alvistack/devel-22.04"},
  "worker03" => {"memory" => "1024", "cpu" => "1", "ip" => "103", "image" => "alvistack/devel-22.04"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      # Para quem tem mais de uma placa de rede física no computador ou notebook, dá para setar qual placa ficará como bridge.
      machine.vm.network "public_network", ip: "10.10.10.#{conf["ip"]}"#, bridge: "enp4s0"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        
      end
      machine.vm.provision "shell", path: "install-docker.sh"
      if "#{name}" == "master"
        machine.vm.provision "shell", path: "master.sh"
      else
        machine.vm.provision "shell", path: "worker.sh"
      end
    end
  end
end